### ISSUE TITLE
Error on pull to SeAT v 1.0.18

### ISSUE THREAD

**Issue by johanko** [awerries/allianceauth_to_seat#1]
Traceback (most recent call last):
  File "import_keys.py", line 80, in <module>
    main(sys.argv[1:])
  File "import_keys.py", line 74, in main
    conf = read_conf_file(conf_file)
  File "import_keys.py", line 53, in read_conf_file
    conf = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 9 column 5 (char 284)

**Comment by johanko** [comment]
missing a , in conf file after token line.

**Comment by awerries** [comment]
Fixed with latest commit.
